### ISSUE TITLE
cxz.to

### ISSUE THREAD

**Issue by hakhagmon** [VitaliyR/telegram-fspls-bot#2]
cxz.to переехал на czx.to, пора бы уже бота обновить

**Comment by VitaliyR** [comment]
@hakhagmon czx это, на сколько мне известно, совершенно другой ресурс, который не имеет никакого отношения к brb, fs, cxz etc. Кроме того, "под капотом" он совершенно другой - нужно писать парсер под него. Возможно, в будущем - сейчас времени нету на это.

**Comment by hakhagmon** [comment]
это часть команды с cxz

**Comment by VitaliyR** [comment]
@hakhagmon где об этом можно прочесть? Я что-то пропустил такую новость.

**Comment by hakhagmon** [comment]
https://vk.com/czxto
